[package]
name = "pds-netanalyzer"
version = "0.1.0"
edition = "2021"

[lib]
name = "netanalyzer"
path = "src/lib/lib.rs"


[dependencies]
pcap = "1.0.0"
clap = { version = "4.0.15", features = ["derive"] }
pktparse = "0.7.1"
serde = { version = "1.0.147", features = ["derive"] }
chrono = "0.4.23"
dns-parser = "0.8.0"